sudo: required

services:
  - docker 


before_install:
  - docker build -t duyguemre/docker-react -f Dockerfile.dev .


script:
  - docker run duyguemre/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
